@startuml
class PasswordGenerator {
- {static} Logger logger
- {static} String LOWERCASE_EN
- {static} String LOWERCASE_RU
- {static} String LOWERCASE_DE
- {static} String UPPERCASE_EN
- {static} String UPPERCASE_RU
- {static} String UPPERCASE_DE
- {static} String SPECIAL_CHARACTERS
- {static} ArrayList<String> LANGUAGES
- {static} Scanner scanner
- {static} SecureRandom random
+ {static} void main(String[])
- {static} int getPasswordLength()
- {static} String[] getSelectedLanguages()
- {static} boolean getYesOrNoInput(String)
- {static} String getCustomDigits()
# {static} String generatePassword(int,String[],boolean,boolean,String,boolean)
- {static} String generateRandomPassword(int,String)
}
@enduml